### ISSUE TITLE
EPIC: User Authentication 

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#1]
The user has the ability to sign up and have a secure account on the website. This feature will also have the option to reset the password in case it's forgotten or it's not deemed safe anymore. 

- [ ] USER STORY: As a user, I want to be able to sign up for an account so that I can access personalized features like creating checklists or leaving comments.
- [ ] USER STORY: As a user, I want to log in securely so that I can access my profile and saved data.
- [ ] USER STORY: As a user, I want to reset my password if I forget it so that I can regain access to my account.
