### ISSUE TITLE
USER STORY: User Sign Up

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#2]
As a **user**, I want to **be able to sign up for an account** so that **access personalized features like creating checklists or leaving comments**.

### Acceptance Criteria

* Acceptance Criteria 1: There should be a *Sign Up* button on the webpage. 
* Acceptance Criteria 2: Once clicked, the user should be directed to a registration form with input validation.
* Acceptance Criteria 3: Once the form is completed, the user should be successfully registered.

### Tasks

- [x]  Implement a *Sign Up* button.
- [x]  Implement a registration form with fields for username, email and password inputs.
- [x]  Write the Django views to handle registration requests and to also ensure usernames and email addresses are unique.
- [x] Display confirmation messages on successful registration and on failed registration errors.
- [x] Test this functionality to ensure everything works properly.
- [ ] Document the feature in the README.md
