### ISSUE TITLE
USER STORY: User Log In

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#3]
As a **user**, I want **to log in securely** so that I can **access my profile and saved data**.

### Acceptance Criteria

* Acceptance Criteria 1: When the user is not logged in, a *Log In* button should come up at the top right corner of the website.
* Acceptance Criteria 2: Once clicked, the user should type in their credentials and their sign in should be successful.

### Tasks

- [x] Implement a *Sign In* button.
- [x] Implement a registration form with fields for username and password inputs.
- [x] Write the Django views to handle login requests.
- [x] Maintain user login status by using the appropriate framework.
- [x] Display confirmation messages on successful and/or failed logins.
- [ ] Test this functionality to ensure everything works properly.
- [ ] Document the feature in the README.md.
