### ISSUE TITLE
USER STORY: User Reset Password

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#4]
As a **user**, I want to **reset my password if I forget it** so that I can **regain access to my account**.

### Acceptance Criteria

* Acceptance Criteria 1: If the user is not logged in, there should be a link that says *Forgot password?* below the *Log In* button.
* Acceptance Criteria 2: When the user clicks on the button, a new page should load where the user is required to type in their email address.
* Acceptance Criteria 3: The user is then sent a link in their inbox where they can safely reset their password.

### Tasks

- [x] Implement a *Forgot Password* button on the *Login* page.
- [x] Write the Django views to handle password reset requests.
- [x] Display a form with an email input for receiving a password reset link.
- [x] Test this functionality to ensure everything works properly.
- [x] Document the feature in the README.md.
