### ISSUE TITLE
USER STORY: Create checklists

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#5]
As a **user**, I want to **to create travel checklists for different trips** so that I can **stay organized**.

### Acceptance Criteria

* Acceptance Criteria 1: The user should be able to create a checklist.
* Acceptance Criteria 2: The user should be able to add bite-sized tasks to their respective checklists.
* Acceptance Criteria 3: User can edit and delete items from the checklist.

### Tasks

- [x] Design models for checklists and items.
- [x] Implement CRUD functionality for checklists and items.
- [x] Test the functionality to ensure it works properly.
- [x] Document the feature in the README.md
