### ISSUE TITLE
USER STORY: Create Blog Posts

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#8]
As a **user**, I want to **write a blog post about my travel experiences** so that I can **share them with others**.

### Acceptance Criteria

* Acceptance Criteria 1: The button *Create Post* will redirect the user to a new page where they can write their post.
* Acceptance Criteria 2: After the post is written and edited, the user can opt to either save it as a draft or publish it.

### Tasks

- [x] Implement a *Create Post* button.
- [x] Add a rich text editor for the user. 
- [x] Allow visibility options for users.
- [x] Test the feature to ensure it works.
- [x] Document the feature in the README.md.
