### ISSUE TITLE
USER STORY: Edit/Delete Blog Posts

### ISSUE THREAD

**Issue by petra66orii** [petra66orii/timeless-travel#9]
As a **user**, I want to **edit or delete my blog posts** so that I can **manage my content**.

### Acceptance Criteria

* Acceptance Criteria 1: When the user clicks on their post, they have an *Edit* button that redirects them to the same page where they first wrote the post.
* Acceptance Criteria 2: At the end of the page, there is a button *Delete Post*. Should the user click on that button, they would be asked for confirmation, and then the post would be deleted.

### Tasks

- [x] Implement a *Edit Post* button. 
- [x] Ensure that the user can only edit/delete their own posts.
- [x] Add a *Delete Post* button under the text editor.
- [x] Add a confirmation message should the user choose to delete the post.
- [x] Test the feature to ensure it works.
- [x] Document the feature in the README.md.
